### PR TITLE
Add Dark Theme

### PR DESCRIPTION
**Pull request by ellieisjelly**
Adds a toggle to the navbar that switches themes.
The user selected theme gets saved to LocalStorage, and thus, is saved between pages and sessions.

### CODE REVIEW

**Comment by Loomeh** [comment]
Hey so I initially merged this as it seemed to run fine on my machine with Live Server but when uploaded to GitHub Pages it has some weird bugs. See attached image.

image

**Comment by ellieisjelly** [comment]
> Hey so I initially merged this as it seemed to run fine on my machine with Live Server but when uploaded to GitHub Pages it has some weird bugs. See attached image.
> 
> image

if you can reproduce this, it'd be of great help if you could send a screenshot of what the description's classes look like

**Comment by Loomeh** [comment]
> > Hey so I initially merged this as it seemed to run fine on my machine with Live Server but when uploaded to GitHub Pages it has some weird bugs. See attached image.
> > image
> 
> if you can reproduce this, it'd be of great help if you could send a screenshot of what the description's classes look like as personally I haven't been able to encounter this issue

Revert to Light Mode on Info page -> go to Home Page.

I'm assuming it's just not updating the colours properly but when I looked through the code I couldn't find anything wrong with it.

**Comment by ellieisjelly** [comment]
> > > Hey so I initially merged this as it seemed to run fine on my machine with Live Server but when uploaded to GitHub Pages it has some weird bugs. See attached image.
> > > image
> > 
> > 
> > if you can reproduce this, it'd be of great help if you could send a screenshot of what the description's classes look like as personally I haven't been able to encounter this issue
> 
> Revert to Light Mode on Info page -> go to Home Page.
> 
> I'm assuming it's just not updating the colours properly but when I looked through the code I couldn't find anything wrong with it.

I can't really reproduce this, could you send a video of it happening?

**Comment by Loomeh** [comment]
> > > > Hey so I initially merged this as it seemed to run fine on my machine with Live Server but when uploaded to GitHub Pages it has some weird bugs. See attached image.
> > > > image
> > > 
> > > 
> > > if you can reproduce this, it'd be of great help if you could send a screenshot of what the description's classes look like as personally I haven't been able to encounter this issue
> > 
> > 
> > Revert to Light Mode on Info page -> go to Home Page.
> > I'm assuming it's just not updating the colours properly but when I looked through the code I couldn't find anything wrong with it.
> 
> I can't really reproduce this, could you send a video of it happening?

I can't as I've already reverted the changes. This seems to be an issue exclusive to GitHub Pages. Create a GitHub Pages environment on your fork and the error should be there.

**Pull request merged**
